### ISSUE TITLE
Avoid countless failed login attempts on windows auth

### ISSUE THREAD

**Issue by PawOrmstrupMadsen** [anaisbetts/ModernHttpClient#218]
Hi

can some who knows more about github help me out.

id like for this code snippet to fix an issue on IOS with windows authentication
if a person tries to login with an incorrect password, the NSUrlSessionHandler will retry forever and in my case the user will be locked out because they only have 3 retries before their account is locked.

`
 if (challenge.PreviousFailureCount == 0 && challenge.ProtectionSpace.AuthenticationMethod == NSUrlProtectionSpace.AuthenticationMethodNTLM) {
                    NetworkCredential credentialsToUse;                   
                    if (This.Credentials != null) {
                        if (This.Credentials is NetworkCredential) {
                            credentialsToUse = (NetworkCredential)This.Credentials;
                        } else {
                            var uri = this.getResponseForTask(task).Request.RequestUri;
                            credentialsToUse = This.Credentials.GetCredential(uri, "NTLM");
                        }
                        var credential = new NSUrlCredential(credentialsToUse.UserName, credentialsToUse.Password, NSUrlCredentialPersistence.ForSession);
                        completionHandler(NSUrlSessionAuthChallengeDisposition.UseCredential, credential);
                    }
                    return;
                }
`

**Comment by Skywanker** [comment]
#225 fixes this
